### ISSUE TITLE
Using this action after reattaching the head

### ISSUE THREAD

**Issue by 403-html** [pr-mpt/actions-merge-branch#5]
Hello, I have question - is there a way of using this action after reattaching HEAD?
I have such example

```yml
steps:
      - name: Reattach HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Merge main branch to PR branch
        uses: pr-mpt/actions-merge-branch@v2
        with:
          from: "origin/main"
```

And I get such error
```sh
Run pr-mpt/actions-merge-branch@v2
Run git config user.name "github-actions[bot]"
Run MERGE="git merge origin/main -s recursive -Xtheirs"
merge: origin/main - not something we can merge
```

**Comment by 403-html** [comment]
ok... I forgot about `fetch-depth`

**Comment by shrink** [comment]
Hi! Thank you for your interest in the Action :) I think this error is because `origin/main` isn't available to git to merge, essentially, the error is "branch not found". I believe this is because you have removed the [`fetch-depth` argument which means it's using the default of `1`](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches).

0 = fetch all history for all branches (which includes `origin/main`)
1 = fetch only the specified ref

I think the following should work:

```yaml
steps:
      - name: Reattach HEAD
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Merge main branch to PR branch
        uses: pr-mpt/actions-merge-branch@v2
        with:
          from: "origin/main"
          fetch-depth: 0
```
